// src/components/ScoreResult/ScoreResult.jsx
import React, { useState, useEffect } from 'react'
import ReactApexChart from 'react-apexcharts'
import SignUpPopup from '../SignUpPopup/SignUpPopup'
import { exportScoreResultToPdf } from '../../services/pdfExport'
import './ScoreResult.scss'

export default function ScoreResult({ score = 30, domainScores = [], recommendations = [] }) {
  const [openDomainIndex, setOpenDomainIndex] = useState(0)
  const [showSignUpPopup, setShowSignUpPopup] = useState(true)

  const chartOptions = {
    chart: { type: 'radar', height: 500, background: 'transparent' },
    xaxis: {
      categories: domainScores.map(d => d.name),
      labels: { style: { colors: '#fff', fontSize: '16px' } }
    },
    yaxis: { show: true, labels: { style: { colors: '#aaa', fontSize: '14px' } } },
    fill: { opacity: 0.3, colors: ['#00d4ff'] },
    stroke: { width: 2, colors: ['#00d4ff'] },
    markers: { size: 4, colors: ['#fff'], strokeColors: ['#00d4ff'] },
    theme: { mode: 'dark' },
    dataLabels: { enabled: false },
    title: {}
  }

  const chartSeries = [{ name: 'Score', data: domainScores.map(d => d.value) }]

  function toggleDomain(i) {
    setOpenDomainIndex(openDomainIndex === i ? null : i)
  }

  async function downloadReport() {
    await exportScoreResultToPdf({ score, domainScores, recommendations })
  }

  return (
    <div className="score-result-wrapper">
      <div className="score-card-gradient-border">
        <div className="score-card">
          <div className="score-title">Your Wealth Score is</div>
          <div className="score-value">{score}</div>
          <div className="score-status">Concerning Financial Health</div>
          <div className="score-description">
            Your financial health is concerning with critical issues that need immediate attention.<br />
            Several aspects of your finances require significant improvement. Focus first on stabilizing your situation by addressing the most pressing vulnerabilities.
          </div>
        </div>
      </div>

      <div className="domain-section">
        <div className="domain-title">Your Domain Scores</div>
        <div className="domain-list">
          {domainScores.map((domain, i) => (
            <div
              key={i}
              className={`domain-item${openDomainIndex === i ? ' open' : ''}`}
              onClick={() => toggleDomain(i)}
              style={{ cursor: 'pointer' }}
            >
              <div className="domain-header">
                <div>
                  <div className="domain-name">{domain.name}</div>
                  <div className="domain-percentage">{domain.percent} of Total Score</div>
                </div>
                <div className="domain-value">
                  {domain.value}
                  <span className="domain-arrow">
                    {openDomainIndex === i ? (
                      <svg width="40" height="40" viewBox="0 0 40 40" fill="none">
                        <path d="M10 24L20 14L30 24" stroke="url(#arrowGradientUp)" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" />
                        <defs>
                          <linearGradient id="arrowGradientUp" x1="10" y1="14" x2="30" y2="24" gradientUnits="userSpaceOnUse">
                            <stop stopColor="#ffb347" /><stop offset="0.5" stopColor="#00c6ff" /><stop offset="1" stopColor="#43e97b" />
                          </linearGradient>
                        </defs>
                      </svg>
                    ) : (
                      <svg width="40" height="40" viewBox="0 0 40 40" fill="none">
                        <path d="M10 16L20 26L30 16" stroke="url(#arrowGradientDown)" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" />
                        <defs>
                          <linearGradient id="arrowGradientDown" x1="10" y1="16" x2="30" y2="26" gradientUnits="userSpaceOnUse">
                            <stop stopColor="#ffb347" /><stop offset="0.5" stopColor="#00c6ff" /><stop offset="1" stopColor="#43e97b" />
                          </linearGradient>
                        </defs>
                      </svg>
                    )}
                  </span>
                </div>
              </div>
              {openDomainIndex === i && (
                domain.summary
                  ? <div className="domain-summary"><b>{domain.summary}</b></div>
                  : domain.description && <div className="domain-description">{domain.description}</div>
              )}
            </div>
          ))}
        </div>
      </div>

      {domainScores.length > 0 && (
        <div className="visualization-section">
          <div className="visualization-title">Score Visualization</div>
          <div className="radar-chart-container">
            <ReactApexChart options={chartOptions} series={chartSeries} type="radar" height={500} />
          </div>
        </div>
      )}

      <div className="recommendations-section">
        <div className="recommendations-title">Recommendations</div>
        <div className="recommendation-list">
          {recommendations.map((rec, i) => (
            <div className="recommendation-item" key={i}>
              <div className="recommendation-title">{rec.title}</div>
              {rec.priority && <div className="recommendation-priority">Priority: {rec.priority}</div>}
              <div className="recommendation-description">{rec.description}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="download-section">
        <button className="download-btn" onClick={downloadReport}>Download Report</button>
      </div>

      <div className="disclaimer">
        Disclaimer: This wealth score is for informational purposes only and should not be considered as financial advice. Please consult with a qualified financial advisor before making any financial decisions.
      </div>

      {showSignUpPopup && (
        <SignUpPopup onClose={() => setShowSignUpPopup(false)} onSkip={() => setShowSignUpPopup(false)} />
      )}
    </div>
  )
}

// src/app/score-result/score-result.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { PdfExportService } from './pdf-export.service';
import { CommonModule } from '@angular/common';
import { NgChartsModule } from 'ng2-charts';
import { trigger, state, style, transition, animate } from '@angular/animations';
import { ApexNonAxisChartSeries, ApexAxisChartSeries, ApexChart, ApexXAxis, ApexDataLabels, ApexPlotOptions, ApexYAxis, ApexStroke, ApexMarkers, ApexFill, ApexTheme, ApexTitleSubtitle, ChartComponent, NgApexchartsModule } from "ng-apexcharts";
import { SignUpPopupComponent } from '../sign-up-popup/sign-up-popup.component';

export type ChartOptions = {
  series: ApexAxisChartSeries;
  chart: ApexChart;
  xaxis: ApexXAxis;
  yaxis: ApexYAxis;
  stroke: ApexStroke;
  markers: ApexMarkers;
  fill: ApexFill;
  theme: ApexTheme;
  dataLabels: ApexDataLabels;
  title: ApexTitleSubtitle;
};

@Component({
  selector: 'app-score-result',
  templateUrl: './score-result.component.html',
  styleUrls: ['./score-result.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    NgChartsModule,
    NgApexchartsModule,
    SignUpPopupComponent
  ],
  animations: [
    trigger('expandCollapse', [
      state('open', style({
        height: '*',
        opacity: 1,
        paddingTop: '12px',
        paddingBottom: '12px',
        marginTop: '8px'
      })),
      state('closed', style({
        height: '0px',
        opacity: 0,
        paddingTop: '0px',
        paddingBottom: '0px',
        marginTop: '0px'
      })),
      transition('open <=> closed', [
        animate('250ms cubic-bezier(.4,0,.2,1)')
      ])
    ])
  ]
})
export class ScoreResultComponent implements OnChanges {
  constructor(private pdfExportService: PdfExportService) {}

  async downloadReport() {
    await this.pdfExportService.exportScoreResultToPdf({
      score: this.score,
      domainScores: this.domainScores,
      recommendations: this.recommendations
    });
  }
  @Input() score: number = 30;
  @Input() domainScores: { 
    name: string; 
    value: number; 
    description?: string; 
    percent?: string; // <-- Change from number to string
    summary?: string; // <-- Add summary to type for type safety
  }[] = [
    {
      name: 'Investment',
      percent: '29%',
      value: 28,
      summary: 'Below-average investment portfolio',
      description: `Your investments require significant attention to improve diversification and contribution levels.
    Your total investments are 0.0x your annual income, which should be increased over time.
    You're currently investing 0.0% of your monthly income, which should be increased.
    Based on your age, your conservative risk profile may be limiting your long-term growth potential.`
    },
    {
      name: 'Debt',
      percent: '23%',
      value: 74,
      summary: 'Good debt management',
      description: `Your debt is generally under control, though there may be opportunities to optimize your debt structure.`
    },
    {
      name: 'Insurance',
      percent: '15%',
      value: 45,
      summary: 'Inadequate insurance coverage',
      description: `Your insurance protection has critical gaps that expose you to significant financial risks. You have no health insurance coverage, exposing you to significant financial risk in case of medical emergencies.`
    }
  ];
  @Input() recommendations: { title: string; priority: string; description: string }[] = [];

  radarChartLabels: string[] = [];
  radarChartData: any = [{ data: [], label: 'Score' }];
  radarChartOptions = {
    responsive: true,
    plugins: {
      legend: { display: false },
      tooltip: { enabled: true }
    },
    scales: {
      r: {
        angleLines: { display: true },
        suggestedMin: 0,
        suggestedMax: 100,
        pointLabels: {
          color: '#fff',
          font: { size: 16 }
        },
        grid: { color: '#444' },
        ticks: { color: '#fff', stepSize: 20 }
      }
    }
  };

  openDomainIndex: number | null = 0; // First card open by default
  showSignUpPopup = true; // Set to true when you want to show the popup

  toggleDomain(index: number) {
    this.openDomainIndex = this.openDomainIndex === index ? null : index;
  }

  ngOnChanges() {
    if (this.domainScores && this.domainScores.length) {
      this.radarChartLabels = this.domainScores.map(d => d.name);
      this.radarChartData = [{
        data: this.domainScores.map(d => d.value),
        label: 'Score',
        backgroundColor: 'rgba(0,212,255,0.2)',
        borderColor: '#00d4ff',
        pointBackgroundColor: '#fff',
        pointBorderColor: '#00d4ff',
        pointHoverBackgroundColor: '#00d4ff',
        pointHoverBorderColor: '#fff'
      }];

      // Update ApexChart options
      this.chartOptions = {
        ...this.chartOptions,
        series: [
          {
            name: 'Score',
            data: this.domainScores.map(d => d.value)
          }
        ],
        chart: {
          type: 'radar',
          height: 500
        },
        xaxis: {
          categories: this.domainScores.map(d => d.name),
          labels: {
            show: true,
            style: {
              colors: '#fff', // or any color you want
              fontSize: '16px'
            }
          }
        },
        yaxis: {
          show: true,
          labels: {
            style: {
              colors: '#aaa',
              fontSize: '14px'
            }
          }
        }
      };
    }
  }

  public chartOptions: Partial<ChartOptions> = {
    series: [],
    chart: {
      type: 'radar', // or the chart type you want
      height: 350
    },
    xaxis: {},
    yaxis: {},
    stroke: {},
    markers: {},
    fill: {},
    theme: {},
    dataLabels: {},
    title: {}
  };
}

<div class="score-result-wrapper">
  <div class="score-card-gradient-border">
    <div class="score-card">
      <div class="score-title">Your Wealth Score is</div>
      <div class="score-value">{{ score }}</div>
      <div class="score-status">Concerning Financial Health</div>
      <div class="score-description">
        Your financial health is concerning with critical issues that need immediate attention.<br />
        Several aspects of your finances require significant improvement. Focus first on stabilizing your situation by addressing the most pressing vulnerabilities.
      </div>
    </div>
  </div>

  <div class="domain-section">
    <div class="domain-title">Your Domain Scores</div>
    <div class="domain-list">
      <div
        class="domain-item"
        *ngFor="let domain of domainScores; let i = index"
        [class.open]="openDomainIndex === i"
        (click)="toggleDomain(i)"
        style="cursor:pointer;"
      >
        <div class="domain-header">
          <div>
            <div class="domain-name">{{ domain.name }}</div>
            <div class="domain-percentage">{{ domain.percent }} of Total Score</div>
          </div>
          <div class="domain-value">
            {{ domain.value }}
            <span class="domain-arrow">
              <ng-container *ngIf="openDomainIndex === i">
                <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M10 24L20 14L30 24" stroke="url(#arrowGradientUp)" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"/>
                  <defs>
                    <linearGradient id="arrowGradientUp" x1="10" y1="14" x2="30" y2="24" gradientUnits="userSpaceOnUse">
                      <stop stop-color="#ffb347"/>
                      <stop offset="0.5" stop-color="#00c6ff"/>
                      <stop offset="1" stop-color="#43e97b"/>
                    </linearGradient>
                  </defs>
                </svg>
              </ng-container>
              <ng-container *ngIf="openDomainIndex !== i">
                <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M10 16L20 26L30 16" stroke="url(#arrowGradientDown)" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"/>
                  <defs>
                    <linearGradient id="arrowGradientDown" x1="10" y1="16" x2="30" y2="26" gradientUnits="userSpaceOnUse">
                      <stop stop-color="#ffb347"/>
                      <stop offset="0.5" stop-color="#00c6ff"/>
                      <stop offset="1" stop-color="#43e97b"/>
                    </linearGradient>
                  </defs>
                </svg>
              </ng-container>
            </span>
          </div>
        </div>
        <div *ngIf="openDomainIndex === i">
          <ng-container *ngIf="domain.summary; else showDescription">
            <div class="domain-summary"><b>{{ domain.summary }}</b></div>
          </ng-container>
          <ng-template #showDescription>
            <div class="domain-description" *ngIf="domain.description">{{ domain.description }}</div>
          </ng-template>
        </div>
      </div>
    </div>
  </div>

  <div class="visualization-section">
    <div class="visualization-title">Score Visualization</div>
    <div class="radar-chart-container">
      <apx-chart
        [series]="chartOptions.series || []"
        [chart]="chartOptions.chart || { type: 'radar', height: 350 }"
        [xaxis]="chartOptions.xaxis || {}"
        [yaxis]="chartOptions.yaxis || {}"
        [stroke]="chartOptions.stroke || {}"
        [markers]="chartOptions.markers || {}"
        [fill]="chartOptions.fill || {}"
        [theme]="chartOptions.theme || {}"
        [dataLabels]="chartOptions.dataLabels || {}"
        [title]="chartOptions.title || {}">
      </apx-chart>
    </div>
  </div>

  <div class="recommendations-section">
    <div class="recommendations-title">Recommendations</div>
    <div class="recommendation-list">
      <div class="recommendation-item" *ngFor="let rec of recommendations">
        <div class="recommendation-title">{{ rec.title }}</div>
        <div class="recommendation-priority">Priority: {{ rec.priority }}</div>
        <div class="recommendation-description">{{ rec.description }}</div>
      </div>
    </div>
  </div>

  <div class="download-section">
    <button class="download-btn" (click)="downloadReport()">Download Report</button>
  </div>

  <div class="disclaimer">
    Disclaimer: This wealth score is for informational purposes only and should not be considered as financial advice. Please consult with a qualified financial advisor before making any financial decisions.
  </div>

  <app-sign-up-popup *ngIf="showSignUpPopup" (close)="showSignUpPopup = false" (skip)="showSignUpPopup = false"></app-sign-up-popup>
</div>
