// src/app/header/header.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
// ...existing imports...
import { SignUpPopupComponent } from '../sign-up-popup/sign-up-popup.component';
import { ActivatedRoute, NavigationEnd, Router } from '@angular/router';
import { filter, Subscription } from 'rxjs';

@Component({
  selector: 'header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
  standalone: false
})
export class HeaderComponent implements OnInit, OnDestroy {
  public isLoggedIn: boolean = false;
  public userName: string = '';
  public userEmail: string = '';
  public showProfileMenu: boolean = false;
  public url: string = '';
  private routeSubscription: Subscription | undefined;
  public isMenuOpen: boolean = false;
  public showSignUpPopup: boolean = false;

  constructor(private router: Router) {
    // Access the path from route
  }

  onGoogleAuth() {
    // Redirect to Google OAuth with login state
    window.location.href = 'http://localhost:3000/oauth2/authorization/google?state=login';
  }

  openSignUpPopup() {
    this.showSignUpPopup = true;
  }

  closeSignUpPopup() {
    this.showSignUpPopup = false;
  }

  ngOnInit() {
    this.router.events
      .pipe(filter(event => event instanceof NavigationEnd))
      .subscribe((event: NavigationEnd) => {
        this.url = event.urlAfterRedirects;
      });
    // Check login status on load
    this.syncLoginState();
    window.addEventListener('storage', this.syncLoginState.bind(this));
    window.addEventListener('focus', this.syncLoginState.bind(this));
    
    // Also check every 2 seconds for login state changes
    setInterval(() => {
      this.syncLoginState();
    }, 2000);
  }

  syncLoginState() {
    const token = localStorage.getItem('auth_token');
    const name = localStorage.getItem('user_name');
    const email = localStorage.getItem('user_email');
    this.isLoggedIn = !!token;
    this.userName = name || '';
    this.userEmail = email || '';
    console.log('Header - Login state synced:', { 
      isLoggedIn: this.isLoggedIn, 
      userName: this.userName,
      userEmail: this.userEmail,
      token: token ? 'exists' : 'missing',
      initial: this.getInitial()
    });
  }

  getInitial(): string {
    if (!this.userName) {
      return '?';
    }
    
    // Get first letter of the first name
    return this.userName.charAt(0).toUpperCase();
  }

  onProfileClick() {
    this.showProfileMenu = !this.showProfileMenu;
  }

  logout() {
    localStorage.removeItem('auth_token');
    localStorage.removeItem('user_name');
    localStorage.removeItem('user_email');
    this.isLoggedIn = false;
    this.userName = '';
    this.userEmail = '';
    this.showProfileMenu = false;
    window.location.reload();
  }

  ngOnDestroy() {
    // Unsubscribe to avoid memory leaks
    if (this.routeSubscription) {
      this.routeSubscription.unsubscribe();
    }
  }

  toggleMenu() {
    this.isMenuOpen = !this.isMenuOpen;
  }

  scrollToSection(section: string) {
    const el = document.getElementById(section);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth' });
    }
  }
}

<div class="container header w-full flex justify-between items-center">
  <!-- Left side: Logo -->
  <div class="logo">
    <p routerLink="/home" class="cursor-pointer">
      MyWealthScore<span class="gradient-text">.ai</span>
    </p>
  </div>

  <!-- Right side: Navigation links and button -->
  <div class="navigation flex items-center desktop-nav">
    <p [ngClass]="{'active': url == '/vision'}" (click)="scrollToSection('vision')">Vision</p>
    <p [ngClass]="{'active': url == '/four-pillars'}" (click)="scrollToSection('four-pillars')">Four Pillars</p>
    <p [ngClass]="{'active': url == '/ai-intelligence'}" (click)="scrollToSection('ai-intelligence')">AI Intelligence</p>
  <ng-container *ngIf="!isLoggedIn">
    <button class="btn btn-primary" (click)="openSignUpPopup()">Sign up</button>
    <app-sign-up-popup *ngIf="showSignUpPopup" mode="header" (close)="closeSignUpPopup()" (skip)="closeSignUpPopup()"></app-sign-up-popup>
  </ng-container>
  <ng-container *ngIf="isLoggedIn">
    <div class="profile-circle" (click)="onProfileClick()">
      <span>{{ getInitial() }}</span>
    </div>
    <div class="profile-menu" *ngIf="showProfileMenu">
      <div class="profile-name">{{ userName }}</div>
      <div class="profile-email">{{ userEmail }}</div>
      <button class="btn btn-primary" (click)="logout()">Logout</button>
    </div>
  </ng-container>
  </div>

  <!-- Hamburger Menu -->
  <button class="hamburger-menu" [class.open]="isMenuOpen" (click)="toggleMenu()" aria-label="Open navigation menu" tabindex="0">
    <span></span>
    <span></span>
    <span></span>
  </button>

  <!-- Mobile Navigation -->
  <div class="mobile-nav" *ngIf="isMenuOpen">
    <p [ngClass]="{'active': url == '/vision'}" (click)="scrollToSection('vision'); toggleMenu()">Vision</p>
    <p [ngClass]="{'active': url == '/four-pillars'}" (click)="scrollToSection('four-pillars'); toggleMenu()">Four Pillars</p>
    <p [ngClass]="{'active': url == '/ai-intelligence'}" (click)="scrollToSection('ai-intelligence'); toggleMenu()">AI Intelligence</p>
    
    <ng-container *ngIf="!isLoggedIn">
      <button class="btn btn-primary" (click)="openSignUpPopup(); toggleMenu()">Sign up</button>
    </ng-container>
    
    <ng-container *ngIf="isLoggedIn">
      <div class="mobile-profile-info">
        <div class="mobile-profile-name">{{ userName }}</div>
        <div class="mobile-profile-email">{{ userEmail }}</div>
        <button class="btn btn-primary" (click)="logout(); toggleMenu()">Logout</button>
      </div>
    </ng-container>
    
    <app-sign-up-popup *ngIf="showSignUpPopup" mode="header" (close)="closeSignUpPopup()" (skip)="closeSignUpPopup()"></app-sign-up-popup>
  </div>
</div>

// src/components/Header/Header.jsx
import React, { useState, useEffect } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import SignUpPopup from '../SignUpPopup/SignUpPopup'
import './Header.scss'

export default function Header() {
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [userName, setUserName] = useState('')
  const [userEmail, setUserEmail] = useState('')
  const [showProfileMenu, setShowProfileMenu] = useState(false)
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const [showSignUpPopup, setShowSignUpPopup] = useState(false)
  const navigate = useNavigate()
  const location = useLocation()

  function syncLoginState() {
    const token = localStorage.getItem('auth_token')
    const name = localStorage.getItem('user_name')
    const email = localStorage.getItem('user_email')
    setIsLoggedIn(!!token)
    setUserName(name || '')
    setUserEmail(email || '')
  }

  useEffect(() => {
    syncLoginState()
    window.addEventListener('storage', syncLoginState)
    window.addEventListener('focus', syncLoginState)
    const interval = setInterval(syncLoginState, 2000)
    return () => {
      window.removeEventListener('storage', syncLoginState)
      window.removeEventListener('focus', syncLoginState)
      clearInterval(interval)
    }
  }, [])

  function getInitial() {
    if (!userName) return '?'
    return userName.charAt(0).toUpperCase()
  }

  function logout() {
    localStorage.removeItem('auth_token')
    localStorage.removeItem('user_name')
    localStorage.removeItem('user_email')
    setIsLoggedIn(false)
    setUserName('')
    setUserEmail('')
    setShowProfileMenu(false)
    window.location.reload()
  }

  function scrollToSection(section) {
    if (location.pathname !== '/home') {
      navigate('/home')
      setTimeout(() => {
        const el = document.getElementById(section)
        if (el) el.scrollIntoView({ behavior: 'smooth' })
      }, 300)
    } else {
      const el = document.getElementById(section)
      if (el) el.scrollIntoView({ behavior: 'smooth' })
    }
  }

  const url = location.pathname

  return (
    <div className="container header w-full flex justify-between items-center">
      <div className="logo">
        <p onClick={() => navigate('/home')} className="cursor-pointer">
          MyWealthScore<span className="gradient-text">.ai</span>
        </p>
      </div>

      <div className="navigation flex items-center desktop-nav">
        <p className={url === '/vision' ? 'active' : ''} onClick={() => scrollToSection('vision')}>Vision</p>
        <p className={url === '/four-pillars' ? 'active' : ''} onClick={() => scrollToSection('four-pillars')}>Four Pillars</p>
        <p className={url === '/ai-intelligence' ? 'active' : ''} onClick={() => scrollToSection('ai-intelligence')}>AI Intelligence</p>

        {!isLoggedIn && (
          <>
            <button className="btn btn-primary" onClick={() => setShowSignUpPopup(true)}>Sign up</button>
            {showSignUpPopup && (
              <SignUpPopup mode="header" onClose={() => setShowSignUpPopup(false)} onSkip={() => setShowSignUpPopup(false)} />
            )}
          </>
        )}

        {isLoggedIn && (
          <>
            <div className="profile-circle" onClick={() => setShowProfileMenu(!showProfileMenu)}>
              <span>{getInitial()}</span>
            </div>
            {showProfileMenu && (
              <div className="profile-menu">
                <div className="profile-name">{userName}</div>
                <div className="profile-email">{userEmail}</div>
                <button className="btn btn-primary" onClick={logout}>Logout</button>
              </div>
            )}
          </>
        )}
      </div>

      <button
        className={`hamburger-menu${isMenuOpen ? ' open' : ''}`}
        onClick={() => setIsMenuOpen(!isMenuOpen)}
        aria-label="Open navigation menu"
      >
        <span></span>
        <span></span>
        <span></span>
      </button>

      {isMenuOpen && (
        <div className="mobile-nav">
          <p className={url === '/vision' ? 'active' : ''} onClick={() => { scrollToSection('vision'); setIsMenuOpen(false) }}>Vision</p>
          <p className={url === '/four-pillars' ? 'active' : ''} onClick={() => { scrollToSection('four-pillars'); setIsMenuOpen(false) }}>Four Pillars</p>
          <p className={url === '/ai-intelligence' ? 'active' : ''} onClick={() => { scrollToSection('ai-intelligence'); setIsMenuOpen(false) }}>AI Intelligence</p>

          {!isLoggedIn && (
            <button className="btn btn-primary" onClick={() => { setShowSignUpPopup(true); setIsMenuOpen(false) }}>Sign up</button>
          )}

          {isLoggedIn && (
            <div className="mobile-profile-info">
              <div className="mobile-profile-name">{userName}</div>
              <div className="mobile-profile-email">{userEmail}</div>
              <button className="btn btn-primary" onClick={() => { logout(); setIsMenuOpen(false) }}>Logout</button>
            </div>
          )}

          {showSignUpPopup && (
            <SignUpPopup mode="header" onClose={() => setShowSignUpPopup(false)} onSkip={() => setShowSignUpPopup(false)} />
          )}
        </div>
      )}
    </div>
  )
}
