// src/app/login-popup/login-popup.component.ts
import { Component, EventEmitter, Output, Inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpClientModule } from '@angular/common/http';

@Component({
  selector: 'app-login-popup',
  standalone: true,
  imports: [CommonModule, FormsModule, HttpClientModule],
  templateUrl: './login-popup.component.html',
  styleUrls: ['./login-popup.component.scss']
})
export class LoginPopupComponent {
  @Output() close = new EventEmitter<void>();
  @Output() showSignUp = new EventEmitter<void>();

  email = '';
  password = '';
  error: string | null = null;

  constructor(@Inject(HttpClient) private http: HttpClient) {}

  onLogin() {
    this.error = null;
    const body = {
      emailOrPhone: this.email,
      password: this.password
    };
    this.http.post<{ token?: string; message?: string; user?: any }>('http://localhost:3000/auth/login', body).subscribe({
      next: (res: { token?: string; message?: string; user?: any }) => {
        if (res.token) {
          localStorage.setItem('auth_token', res.token);
          
          // Save user email from login form as fallback
          let userEmail = this.email;
          
          // Try to decode JWT to get email and name if available
          let userName = userEmail.split('@')[0]; // Default to first part of email
          try {
            const payload = JSON.parse(atob(res.token.split('.')[1]));
            console.log('JWT payload:', payload);
            if (payload.email) {
              userEmail = payload.email;
            } else if (payload.sub) {
              userEmail = payload.sub; // Email is in 'sub' field
            }
            // Try to get name from JWT payload
            if (payload.name) {
              userName = payload.name;
            } else if (payload.given_name) {
              userName = payload.given_name;
            }
          } catch (e) {
            console.log('Could not decode JWT, using form email', e);
          }
          
          // Check if user object has name information
          if (res.user && res.user.name) {
            userName = res.user.name;
          }
          
          // Save user info
          localStorage.setItem('user_name', userName);
          localStorage.setItem('user_email', userEmail);
          
          console.log('Saved user info:', { userEmail, token: res.token });
          
          alert('Login successful!');
          this.close.emit();
          
          // Force reload to update header state
          window.location.reload();
        } else {
          this.error = res.message || 'Login failed.';
        }
      },
      error: (err: any) => {
        console.error('Login error:', err);
        if (err.status === 0 || err.message?.includes('ERR_CONNECTION_REFUSED')) {
          this.error = 'Server is not available. Please try again later.';
        } else if (err.status === 404) {
          this.error = 'Please try again. Please contact support.';
        } else if (err.status === 401) {
          this.error = 'Invalid email or password. Please try again.';
        } else if (err.status >= 500) {
          this.error = 'Server error. Please try again later.';
        } else {
          this.error = err.error?.message || 'Login failed. Please try again.';
        }
      }
    });
  }

  onClose() {
    this.close.emit();
  }

  onShowSignUp() {
    this.showSignUp.emit();
  }
}

<div class="login-popup-backdrop">
  <div class="login-popup-modal">
    <button class="login-close-btn" (click)="onClose()" aria-label="Close" style="position:absolute;top:18px;right:18px;background:none;border:none;cursor:pointer;font-size:1.7rem;color:#fff;z-index:10;">&times;</button>
      <div *ngIf="error" class="error-message" style="background: #ff4444; color: white; padding: 12px; border-radius: 8px; margin-bottom: 16px; text-align: center;">{{ error }}</div>
  
  <div class="login-popup-title">Login to your account</div>
    <div class="login-popup-desc">Enter your email and password to access your personalized Wealth Score.</div>
    <form class="login-form" (ngSubmit)="onLogin()">
      <input class="login-input" type="email" placeholder="Email" [(ngModel)]="email" name="email" required />
      <input class="login-input" type="password" placeholder="Password" [(ngModel)]="password" name="password" required />
      <button class="login-btn" type="submit" [disabled]="!email || !password">Login</button>
    </form>
    <div class="login-popup-bottom">
      <hr class="login-popup-divider" />
      <div class="login-popup-signup-text">
        Don't have an account?
        <a class="login-popup-signup-link" (click)="onShowSignUp()">Sign up</a>
      </div>
    </div>
  </div>
</div>

// src/components/LoginPopup/LoginPopup.jsx
import React, { useState } from 'react'
import axios from 'axios'
import './LoginPopup.scss'

export default function LoginPopup({ onClose, onShowSignUp }) {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState(null)

  async function onLogin(e) {
    e.preventDefault()
    setError(null)
    try {
      const res = await axios.post('http://localhost:3000/auth/login', {
        emailOrPhone: email,
        password
      })
      if (res.data.token) {
        localStorage.setItem('auth_token', res.data.token)
        let userEmail = email
        let userName = email.split('@')[0]
        try {
          const payload = JSON.parse(atob(res.data.token.split('.')[1]))
          if (payload.email) userEmail = payload.email
          else if (payload.sub) userEmail = payload.sub
          if (payload.name) userName = payload.name
          else if (payload.given_name) userName = payload.given_name
        } catch (e) {}
        if (res.data.user?.name) userName = res.data.user.name
        localStorage.setItem('user_name', userName)
        localStorage.setItem('user_email', userEmail)
        alert('Login successful!')
        onClose()
        window.location.reload()
      } else {
        setError(res.data.message || 'Login failed.')
      }
    } catch (err) {
      if (!err.response) setError('Server is not available. Please try again later.')
      else if (err.response.status === 401) setError('Invalid email or password. Please try again.')
      else if (err.response.status >= 500) setError('Server error. Please try again later.')
      else setError(err.response?.data?.message || 'Login failed. Please try again.')
    }
  }

  return (
    <div className="login-popup-backdrop">
      <div className="login-popup-modal">
        <button className="login-close-btn" onClick={onClose} aria-label="Close">&times;</button>
        {error && (
          <div style={{ background: '#ff4444', color: 'white', padding: '12px', borderRadius: '8px', marginBottom: '16px', textAlign: 'center' }}>{error}</div>
        )}
        <div className="login-popup-title">Login to your account</div>
        <div className="login-popup-desc">Enter your email and password to access your personalized Wealth Score.</div>
        <form className="login-form" onSubmit={onLogin}>
          <input className="login-input" type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} required />
          <input className="login-input" type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} required />
          <button className="login-btn" type="submit" disabled={!email || !password}>Login</button>
        </form>
        <div className="login-popup-bottom">
          <hr className="login-popup-divider" />
          <div className="login-popup-signup-text">
            Don't have an account?
            <a className="login-popup-signup-link" onClick={onShowSignUp} style={{ cursor: 'pointer' }}>Sign up</a>
          </div>
        </div>
      </div>
    </div>
  )
}
